dataset_name: VIFSPDAT #VISPDAT

raw_root: /projects/simlai1/Viberank/data/VibeRank/raw/hmls
processed_root: /projects/simlai1/Viberank/data/VibeRank/processed/pairwise_comparisons/hmls

prompt_filename: prompt_vulnerability.txt
selected_households_filename: selected_households.csv
responses_dirname: responses
flat_selected_dirname: _selected_jsons

tie_sheet_mode: full_ordered_matrix
clear_flat_selected_dir: true

selected_filters:
  drop_missing_uid: true
  drop_missing_band: true

run_settings:
  repeats_per_ordered_pair: 10